- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: Linux, Shell, Ansible, Terraform
    tagMap:
      name: Ansible
      project: roboshop
      environment: dev
    full_name: m.vijaya vamsi
    ip_address: 172.31.27.21
    tagsList: [
        {
            "key": "name",
            "value": "Ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "environment",
            "value": "dev"
        }
    ]

  tasks:
  - name: convert string to list
    debug:
      msg: "Topics are: {{ topics | split(',')}}"

  - name: Set default value
    debug:
      msg: "Hi, {{ GREETING | default('GOOD MORNING') }}"

  - name: convert map to list
    debug:
      msg: "{{ tagMap | dict2items }}"

  - name: convert list to map
    debug:
      msg: "{{ tagsList | items2dict }}"

  - name: convert to upper case
    debug:
      msg: "{{ full_name | upper }}"  

  - name: convert to lower case
    debug:
      msg: "{{ full_name | lower }}"  

  - name: to check ip is valid or not
    debug:
      msg: "{{ ip_address | ansible.utils.ipv4 }}" 


